### ISSUE TITLE
IndexError while Parsing MIDI

### ISSUE THREAD

**Issue by josepdecid** [timwedde/py_midicsv#2]
First of all, congrats for this Python library, which makes easier and integrable the parsing from MIDI files to CSV in Python. I'm encountering a problem while parsing a certain file, which gives the following error:

> Traceback (most recent call last):
  File "/Users/josepdecidrodriguez/Google Drive/IU/AML/Project/BachPropagation/src/dataset/parser.py", line 27, in <module>
    data = py_midicsv.midi_to_csv(file)
  File "/Users/josepdecidrodriguez/Envs/BachPropagation-L4F7V3ER/lib/python3.7/site-packages/py_midicsv/midicsv.py", line 31, in parse
    csv_file.append(midi_to_csv_map[type(event)](index + 1, abstime, event))
  File "/Users/josepdecidrodriguez/Envs/BachPropagation-L4F7V3ER/lib/python3.7/site-packages/py_midicsv/midi_converters.py", line 117, in from_KeySignatureEvent
    return write_event(track, time, "Key_signature", [event.get_alternatives(), '"major"' if event.data[1] == 0 else '"minor"'])
IndexError: list index out of range

This is given by the following file [BWV_809____piano.txt](https://github.com/timwedde/py_midicsv/files/2970584/BWV_809____piano.txt) (I've changed the extension to .txt to be able to upload it here).

**Comment by timwedde** [comment]
Could you provide the original input file that generates this error?
This would allow me to replicate it on my end.

**Comment by timwedde** [comment]
Could you provide the original input file that generates this error?

**Comment by timwedde** [comment]
I have released 1.8.2 which contains a fix for this issue.
Apparently I missed a condition where some event data would not exist but I tried accessing it anyway.

**Comment by josepdecid** [comment]
Great! I was about to do a PR fixing the problem 👍

**Comment by timwedde** [comment]
No problem :)
If you find anything else that's going wrong or could stand an improvement, don't hesitate to send a PR or open an Issue.
