### ISSUE TITLE
csv export

### ISSUE THREAD

**Issue by patricio1979** [timwedde/py_midicsv#8]
Can we export a cvs file from MIDI?
Do you have an example? (new to python)

**Comment by timwedde** [comment]
An example exists right there [in the README file](https://github.com/timwedde/py_midicsv#usage).

**Comment by patricio1979** [comment]
But I need to export a csv file, not a MIDI. The example file exports to MIDI, how can I render a csv?

**Comment by timwedde** [comment]
The example does both conversions. Simply write the `csv_string` to disk instead of the midi file if you so desire.

**Comment by timwedde** [comment]
Closing this due to a lack of response. If you still have issues, feel free to reopen.
